mongo-addr: localhost:27017
api-addr: :8081
auth-username: admin
auth-password: password
location: 'http://localhost:8081'
private-key: 8PjzjakvIlh3BVFKe8axinRDutF6EDIfjtuf4+JaNow=
public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
access-log: access.log
max-mgo-sessions: 300
request-timeout: 2s
private-addr: localhost
tls-cert: |
  -----BEGIN CERTIFICATE-----
  MIIBbDCCARYCCQCSJb9RIECG3TANBgkqhkiG9w0BAQsFADA9MQswCQYDVQQGEwJT
  STETMBEGA1UECAwKU29tZS1TdGF0ZTENMAsGA1UECgwEanVqdTEKMAgGA1UEAwwB
  KjAeFw0xNjA4MDcxOTIxMTJaFw0xNzA4MDcxOTIxMTJaMD0xCzAJBgNVBAYTAlNJ
  MRMwEQYDVQQIDApTb21lLVN0YXRlMQ0wCwYDVQQKDARqdWp1MQowCAYDVQQDDAEq
  MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMnPMI1t2amkSWJKPnjScnIblL67W6Aj
  1+82fWZYwfP81zv8u5AAsfYa68o2yzfT14vvWmCFaN53VHpz1xI47f0CAwEAATAN
  BgkqhkiG9w0BAQsFAANBALT0/5yGpaGP9RaD+xRdoxGFf9m7g2IXUphlyN+KD4ST
  kjzzw0795c5I6Mt2HSbi7P+hP+9MGWi0jWpoO2Xj8M4=
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIBbDCCARYCCQCSJb9RIECG3TANBgkqhkiG9w0BAQsFADA9MQswCQYDVQQGEwJT
  STETMBEGA1UECAwKU29tZS1TdGF0ZTENMAsGA1UECgwEanVqdTEKMAgGA1UEAwwB
  KjAeFw0xNjA4MDcxOTIxMTJaFw0xNzA4MDcxOTIxMTJaMD0xCzAJBgNVBAYTAlNJ
  MRMwEQYDVQQIDApTb21lLVN0YXRlMQ0wCwYDVQQKDARqdWp1MQowCAYDVQQDDAEq
  MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMnPMI1t2amkSWJKPnjScnIblL67W6Aj
  1+82fWZYwfP81zv8u5AAsfYa68o2yzfT14vvWmCFaN53VHpz1xI47f0CAwEAATAN
  BgkqhkiG9w0BAQsFAANBALT0/5yGpaGP9RaD+xRdoxGFf9m7g2IXUphlyN+KD4ST
  kjzzw0795c5I6Mt2HSbi7P+hP+9MGWi0jWpoO2Xj8M4=
  -----END CERTIFICATE-----
tls-key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIBOwIBAAJBAMnPMI1t2amkSWJKPnjScnIblL67W6Aj1+82fWZYwfP81zv8u5AA
  sfYa68o2yzfT14vvWmCFaN53VHpz1xI47f0CAwEAAQJBAMIh8Y7bkXtDcuR+j0Ij
  D7z9E0W3bhjK4jpXrKH71/ggFtyAJ/guMIlIZVcHqnjMcfu4nPrJDavWK/6F+A5S
  DQECIQD4Nr921aDOvJf9wyZu9Vl2fj+4w3i7jrDLDIwNpXx9zQIhANAjy7K4wf15
  kY3CiD24vrd+++uJPdNIhAYjKkYNoIDxAiEAzqDc4LNUS+YJ7VEwxHvwvsi4iToI
  XrKZkF7glFen/B0CIA3RgpGQAJkSfB5cPu1SGZ9XF+SQTQF8+/7oUMMr3m8RAiA0
  X9RasyDocy/n3dUGVMqum9O1QwAoBwu+AzgRqOECVA==
  -----END RSA PRIVATE KEY-----
admin-agent-public-key: iKp24EL2Aj9MQfRkpwzp7rz7Zf3QZsEzWGpoWT3OK2w=
